import type { ContentDictionary } from '../../localise';

/**
 * `african-central-banks` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const africanCentralBanksPtPT: ContentDictionary = {
  'module.title': 'Bancos Centrais Africanos e o Franco CFA',
  'module.description': 'Catorze países, duas moedas com o mesmo nome, e uma paridade fixada em 655,957 desde 1999. O que era a conta em Paris, o que mudou em 2020, e quem suporta o custo de uma taxa que não se pode mexer.',
};
