import type { ContentDictionary } from '../../localise';

/**
 * `banking-and-money` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const bankingAndMoneyPtPT: ContentDictionary = {
  'module.title': 'Banca e Dinheiro (Khan Academy)',
  'module.description': 'Sal Khan constrói o sistema bancário a partir de uma ilha, um cofre e mil moedas de ouro — passando pelas reservas fracionárias, a alavancagem, o banco central e as operações de mercado aberto, até ao balanço real da Fed. Vinte e cinco vídeos, cada um com perguntas escritas a partir do que ele diz de facto, a acabar no argumento dele próprio contra o sistema que acabou de explicar.',
};
