import type { ContentDictionary } from '../../localise';

/**
 * `breaking-a-peg-1992` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const breakingAPeg1992PtPT: ContentDictionary = {
  'module.title': 'Quebrar uma Paridade: setembro de 1992',
  'module.description': 'A operação sobre a libra, feita em contas e não em anedota: porque é que a posição no MTC era insustentável, porque é que atacar uma paridade só custa o carry, o que se gasta de facto a defendê-la, e a aritmética da Quarta-Feira Negra.',
};
