import type { ContentDictionary } from '../../localise';

/**
 * `buying-property-portugal` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const buyingPropertyPortugalPtPT: ContentDictionary = {
  'module.title': 'Comprar Casa em Portugal: As Contas',
  'module.description': 'IMT, Imposto do Selo, IMI, manutenção e a comissão da imobiliária, ao euro — e quantos anos de valorização são precisos para os cobrir. Depois comprar contra arrendar, e o mesmo apartamento comprado só para dar lucro.',
};
