import type { ContentDictionary } from '../../localise';

/**
 * `commercial-central-interface` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const commercialCentralInterfacePtPT: ContentDictionary = {
  'module.title': 'A Interface entre Banca Comercial e Banco Central',
  'module.description': 'Como se liquida realmente um pagamento, porque é que os bancos têm reservas, e o que limita mesmo o crédito.',
};
