import type { ContentDictionary } from '../../localise';

/**
 * `course` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const coursePtPT: ContentDictionary = {
  'course.title': 'Fundamentos de Macroeconomia',
  'course.description': 'Dinheiro, banca e política monetária — construídos desde o princípio, cinco minutos de cada vez.',
};
