import type { ContentDictionary } from '../../localise';

/**
 * `crisis-architecture-global-dollar` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const crisisArchitectureGlobalDollarPtPT: ContentDictionary = {
  'module.title': 'Arquitetura de Crise e o Dólar Global',
  'module.description': 'Dólares offshore, linhas de swap, resolução e o laço fatal — e como distinguir um tipo de crise de outro.',
};
