import type { ContentDictionary } from '../../localise';

/**
 * `debt-debasement-and-capital` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const debtDebasementAndCapitalPtPT: ContentDictionary = {
  'module.title': 'Dívida, Aviltamento da Moeda e Capital',
  'module.description': 'Quem paga de facto uma dívida que nunca é reembolsada, o que o aviltamento da moeda historicamente serviu para financiar, e o que os mesmos recursos constroem quando vão antes para capital.',
};
