import type { ContentDictionary } from '../../localise';

/**
 * `euribor` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const euriborPtPT: ContentDictionary = {
  'module.title': 'Euribor',
  'module.description': 'A taxa a que é revisto quase todo o crédito à habitação da zona euro, e que quase ninguém sabe definir bem. O que mede, porque é que se mexe antes do BCE, quanto custa uma revisão — e cinco perguntas que separam saber de perceber.',
};
