import type { ContentDictionary } from '../../localise';

/**
 * `fed-ecb-levers` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const fedEcbLeversPtPT: ContentDictionary = {
  'module.title': 'As Alavancas da Fed e do BCE',
  'module.description': 'IORB, o piso da ON RRP, a janela de redesconto e o corredor da DFR — lançamento a lançamento.',
};
