import type { ContentDictionary } from '../../localise';

/**
 * `foundations-fiduciary-currency` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const foundationsFiduciaryCurrencyPtPT: ContentDictionary = {
  'module.title': 'Fundamentos da Moeda Fiduciária',
  'module.description': 'Porque é que se aceita papel sem lastro, o que é realmente a inflação, e o que se parte quando uma moeda falha.',
};
