import type { ContentDictionary } from '../../localise';

/**
 * `reading-the-fed-balance-sheet` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const readingTheFedBalanceSheetPtPT: ContentDictionary = {
  'module.title': 'Ler o Balanço da Fed',
  'module.description': 'O H.4.1 verdadeiro, linha a linha: o que a Fed tem, quem detém o seu passivo, e porque é que as reservas são o que sobra. Números tal como reportados a 2 de setembro de 2026.',
};
