import type { ContentDictionary } from '../../localise';

/**
 * `reading-the-ecb-balance-sheet` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const readingTheEcbBalanceSheetPtPT: ContentDictionary = {
  'module.title': 'Ler o Balanço do BCE',
  'module.description': 'A situação semanal do Eurosistema face à da Fed: um quinto dela em ouro, duas contas de reservas em vez de uma, e um quadro de cedência de que já não precisa. Números a 28 de agosto de 2026.',
};
