import type { ContentDictionary } from '../../localise';

/**
 * `real-assets-and-property` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const realAssetsAndPropertyPtPT: ContentDictionary = {
  'module.title': 'Ativos Reais e o Preço de uma Morada',
  'module.description': 'O dinheiro cresceu 69%, os preços no consumidor 32%, as casas 60%. Porque é que ter imóveis durante isso transfere riqueza de quem tinha euros, o que põe um chão debaixo de um preço — e porque é que Dublin ainda assim caiu para metade.',
};
