import type { ContentDictionary } from '../../localise';

/**
 * `scrutinising-cbdcs` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const scrutinisingCbdcsPtPT: ContentDictionary = {
  'module.title': 'Analisar as CBDC: o Projeto Mariana',
  'module.description': 'Uma experiência do BIS, lida como deve ser. O que uma CBDC grossista muda e o que não muda, o que a Mariana construiu de facto, quanto custa a liquidação instantânea em liquidez parada, que funcionalidades de controlo são novas — e quem teria de dizer que sim antes de qualquer disto ser dinheiro.',
};
