import type { ContentDictionary } from '../../localise';

/**
 * `the-treasury-yield-curve` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const theTreasuryYieldCurvePtPT: ContentDictionary = {
  'module.title': 'A Curva de Rendimentos do Tesouro',
  'module.description': 'Um só devedor, onze maturidades, onze taxas. Porque é que preço e yield são o mesmo número, o que diz realmente uma inversão, e como ler a curva tal como publicada a 3 de setembro de 2026.',
};
