import type { ContentDictionary } from '../../localise';

/**
 * `the-bis-and-the-ecb` — pt-PT.
 *
 * Generated by `npm run i18n:import`. Notes above the line below survive.
 */

// ─── generated below · `npm run i18n:import` rewrites from here ───────────

export const theBisAndTheEcbPtPT: ContentDictionary = {
  'module.title': 'O BIS e o BCE',
  'module.description': 'Que canais de influência entre Basileia e Frankfurt são reais: normas que têm de passar por um parlamento, investigação que fixa os termos do debate, estatísticas que mais ninguém recolhe — e quais funcionam ao contrário.',
};
