/**
 * ============================================================================
 * `npm run i18n:import -- <locale>`
 * ============================================================================
 *
 * Reads `translations/<locale>/*.json` back into the TypeScript catalogues.
 *
 * This is the half that was missing, and its absence is what made translation
 * a developer-only activity: extraction could hand work out, and nothing could
 * take it back. A translator finishing a module had to send a file to someone
 * who would paste 227 strings by hand.
 *
 * ---------------------------------------------------------------------------
 * IMPORT IS WHERE BAD DATA ENTERS, SO IT IS WHERE VALIDATION LIVES
 * ---------------------------------------------------------------------------
 *
 * A translator works in a spreadsheet or a web tool, not in TypeScript, and
 * the two mistakes that come back are a renamed placeholder (`{nome}` for
 * `{name}`) and an unbalanced brace. Both produce a string that compiles and
 * renders as nonsense.
 *
 * Every unit is checked before it is written, and a unit that fails is
 * **rejected rather than written** — the previous translation stays, the key
 * falls back to English if there was none, and the report says exactly which
 * string and why. Importing a file with three bad strings should cost you
 * three strings, not the file.
 *
 * The same rules run again in CI via `i18n:status --strict`, because a file
 * can also be edited by hand after import.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  entries,
  fingerprint,
  localeSuffix,
  localeSymbol,
  moduleSymbol,
  tsString,
  writeGenerated,
} from './i18n-files.mjs';
import { TRANSLATIONS_DIR, readState, statePath } from './i18n-extract.mjs';

/** Balanced braces, and no argument the English source does not provide. */
export function checkUnit({ key, source, target, argumentsOf }) {
  let depth = 0;
  for (const char of target) {
    if (char === '{') depth += 1;
    else if (char === '}') depth -= 1;
    if (depth < 0) break;
  }
  if (depth !== 0) return `unbalanced braces`;

  const allowed = argumentsOf(source);
  for (const name of argumentsOf(target)) {
    if (!allowed.has(name)) return `uses {${name}}, which the English source does not provide`;
  }
  return null;
}

/**
 * Read every scope file for a locale.
 *
 * Returns `{ ui, modules, course }` of accepted translations, plus the
 * rejections, so the caller can report before anything is written.
 */
export function collect(locale, argumentsOf) {
  const dir = join(TRANSLATIONS_DIR, locale);
  if (!existsSync(dir)) {
    return { error: `No translations at ${dir}. Run: npm run i18n:extract -- ${locale}` };
  }

  const files = readdirSync(dir).filter((name) => name.endsWith('.json')).sort();
  if (files.length === 0) return { error: `No .json files in ${dir}.` };

  const accepted = {};
  const rejected = [];
  const skipped = [];

  for (const file of files) {
    const scope = file.replace(/\.json$/, '');
    let document;
    try {
      document = JSON.parse(readFileSync(join(dir, file), 'utf8'));
    } catch (cause) {
      rejected.push({ scope, key: '(whole file)', reason: `not valid JSON — ${cause.message}` });
      continue;
    }
    if (document.locale && document.locale !== locale) {
      rejected.push({
        scope,
        key: '(whole file)',
        reason: `declares locale "${document.locale}", imported as "${locale}"`,
      });
      continue;
    }

    const out = {};
    for (const [key, unit] of Object.entries(document.units ?? {})) {
      const target = typeof unit?.target === 'string' ? unit.target.trim() : '';
      const source = typeof unit?.source === 'string' ? unit.source : '';
      if (!target) {
        skipped.push({ scope, key });
        continue;
      }
      const problem = checkUnit({ key, source, target, argumentsOf });
      if (problem) {
        rejected.push({ scope, key, reason: problem });
        continue;
      }
      out[key] = { target, source };
    }
    accepted[scope] = out;
  }

  return { accepted, rejected, skipped };
}

// ---------------------------------------------------------------------------
// Writing the catalogues
// ---------------------------------------------------------------------------

const UI_HEADER = (locale) => `import type { UiDictionary } from './en';

/**
 * Interface strings — ${locale}.
 *
 * Generated by \`npm run i18n:import\`. Anything above the line below is
 * hand-written and preserved across imports; put translator notes there —
 * the conventions a language has settled on are worth far more to the next
 * person than the strings are.
 */

`;

const CONTENT_HEADER = (locale, moduleId) => `import type { ContentDictionary } from '../../localise';

/**
 * \`${moduleId}\` — ${locale}.
 *
 * Generated by \`npm run i18n:import\`. Notes above the line below survive.
 */

`;

export function writeUi(locale, translations) {
  const path = join('packages/core/src/i18n/ui', `${locale}.ts`);
  const body = `export const ${localeSymbol(locale)}: UiDictionary = {\n${entries(translations)}\n};\n`;
  writeGenerated(path, UI_HEADER(locale), body);
  return path;
}

export function writeCourse(locale, translations) {
  const dir = join('packages/core/src/i18n/content', locale);
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'course.ts');
  const body = `export const course${localeSuffix(locale)}: ContentDictionary = {\n${entries(translations)}\n};\n`;
  writeGenerated(path, CONTENT_HEADER(locale, 'course'), body);
  return path;
}

export function writeModule(locale, moduleId, translations) {
  const dir = join('packages/core/src/i18n/content', locale);
  mkdirSync(dir, { recursive: true });
  const path = join(dir, `${moduleId}.ts`);
  const symbol = `${moduleSymbol(moduleId)}${localeSuffix(locale)}`;
  const body = `export const ${symbol}: ContentDictionary = {\n${entries(translations)}\n};\n`;
  writeGenerated(path, CONTENT_HEADER(locale, moduleId), body);
  return path;
}

/**
 * Rewrite the locale's content index so an imported module is registered
 * without anyone editing a file.
 *
 * Module overlays are spread *after* the headings, so a fully translated
 * module's own title wins over the headings file's copy of it.
 */
export function writeContentIndex(locale, moduleIds, { hasCourse }) {
  const path = join('packages/core/src/i18n/content', locale, 'index.ts');
  const suffix = localeSuffix(locale);
  const imports = [
    `import type { ContentTranslation } from '../index';`,
    hasCourse ? `import { course${suffix} } from './course';` : null,
    ...moduleIds.map((id) => `import { ${moduleSymbol(id)}${suffix} } from './${id}';`),
  ].filter(Boolean);

  const modules = moduleIds.map((id) => `    ${tsString(id)}: ${moduleSymbol(id)}${suffix},`);

  const body = `export const ${localeSymbol(locale)}Content: ContentTranslation = {
${hasCourse ? `  course: course${suffix},\n` : ''}  modules: {
${modules.join('\n')}
  },
};
`;

  /**
   * Written whole, with no preserved region — unlike the catalogues.
   *
   * The import list at the top *is* the generated part: registering a newly
   * translated module means adding an import, so a preserved header would
   * freeze the very thing that has to change. There is nothing here worth
   * hand-writing, and the banner says so.
   */
  const file = `// GENERATED FILE — do not edit. Run \`npm run i18n:import -- ${locale}\`.
//
// A module is registered here by being imported, so translating one is a file
// arriving rather than a file arriving and somebody remembering to wire it up.
// Hand-written notes belong in the catalogue files themselves, which keep
// everything above their generated-region marker.

${imports.join('\n')}

${body}`;
  writeFileSync(path, file, 'utf8');
  return path;
}

/**
 * Record what the English said, so the next extract can spot a drift.
 *
 * Nested by scope, because content keys are only unique *within* a module:
 * every one of the seventeen has a `module.title`, with seventeen different
 * English strings behind it. A flat map meant the last module imported won,
 * and every other module's title then disagreed with the recorded
 * fingerprint — so changing one English string reported thirty-three stale
 * translations, thirty-two of which were the bug.
 */
export function writeState(locale, accepted) {
  const state = readState(locale);
  for (const [scope, units] of Object.entries(accepted)) {
    const bucket = state[scope] ?? (state[scope] = {});
    for (const [key, { source }] of Object.entries(units)) {
      if (source) bucket[key] = fingerprint(source);
    }
  }
  const path = statePath(locale);
  mkdirSync(join('packages/core/src/i18n/state'), { recursive: true });
  const ordered = Object.fromEntries(
    Object.keys(state)
      .sort()
      .map((scope) => [
        scope,
        Object.fromEntries(Object.keys(state[scope]).sort().map((key) => [key, state[scope][key]])),
      ]),
  );
  writeFileSync(path, `${JSON.stringify(ordered, null, 2)}\n`, 'utf8');
  return path;
}
